edition = "2024"
max_width = 100
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
indent_style = "Block"
reorder_imports = true
fn_params_layout = "Compressed"
match_block_trailing_comma = true
# Unstable features below
style_edition = "2024"
comment_width = 100
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
normalize_comments = true
normalize_doc_attributes = true
unstable_features = true
wrap_comments = true
error_on_line_overflow = true
error_on_unformatted = true
overflow_delimited_expr = false
fn_single_line = false
where_single_line = true
reorder_impl_items = true
combine_control_expr = false
struct_field_align_threshold = 25
enum_discrim_align_threshold = 25
match_arm_blocks = false
